package models

const (
	AuthenticationError = "authentication_error"
	BadGateway = "bad_gateway"
	BlockedIPAddress = "blocked_ip_address"
	DisabledHLR = "disabled_hlr"
	DisabledMemo = "disabled_memo"
	DisabledOriginalURLCode = "disabled_original_url_code"
	DisabledRCS = "disabled_rcs"
	DisabledResending ="disabled_resending"
	DisabledSMSText = "disabled_sms_text"
	DisabledThirdPartyAPI = "disabled_third_party_api"
	DisabledSMSTitleFunction = "disabled_sms_title"
	DocomoBasicSMSTextTooLong = "docomo_basic_sms_text_too_long"
	DocomoReminderTextTooLong = "docomo_reminder_text_too_long"
	DuplicatedSMSId = "duplicated_sms_id"
	InvalidAuTitle = "invalid_au_title"
	InvalidAuTTL = "invalid_au_ttl"
	InvalidBasicSMSText = "invalid_basic_sms_text"
	InvalidDocomoSMSText = "invalid_docomo_sms_text"
	InvalidDocomoTitle = "invalid_docomo_title"
	InvalidDocomoTTL = "invalid_docomo_ttl"
	InvalidDispatchTime = "invalid_dispatch_time"
	InvalidJSONFormat = "invalid_json_format"
	InvalidKeepChatID = "invalid_keep_chat_id"
	InvalidGatewayTTL = "invalid_gateway_ttl"
	InvalidOriginalURL = "invalid_original_url"
	InvalidOriginalURLTwo = "invalid_original_url_two"
	InvalidOriginalURLThree = "invalid_original_url_three"
	InvalidOriginalURLFour = "invalid_original_url_four"
	InvalidOriginalURLCode = "invalid_original_url_code"
	InvalidOriginalURLCodeTwo = "invalid_original_url_code_two"
	InvalidOriginalURLCodeThree = "invalid_original_url_code_three"
	InvalidOriginalURLCodeFour = "invalid_original_url_code_four"
	InvalidRakutenTitle = "invalid_rakuten_title"
	InvalidRakutenText = "invalid_rakuten_text"
	InvalidRakutenTTL = "invalid_rakuten_ttl"
	InvalidReminderDelay = "invalid_reminder_delay"
	InvalidReminderText = "invalid_reminder_text"
	InvalidRegistrationDate = "invalid_registration_date"
	InvalidResendingInterval = "invalid_resending_interval"
	InvalidReturnSMS = "invalid_return_sms"
	InvalidReplyID = "invalid_reply_id"
	InvalidSendingAttempts = "invalid_sending_attempts"
	InvalidSendDateTime = "invalid_send_date_time"
	InvalidStatus = "invalid_status"
	InvalidSMSID = "invalid_smsid"
	InvalidSIMTitle = "invalid_sim_title"
	InvalidSoftbankTitle = "invalid_softbank_title"
	InvalidSoftbankTTL = "invalid_softbank_ttl"
	InvalidSMSBody = "invalid_sms_body"
	InvalidSMSTextID = "basic_sms_text_id"
	InvalidSMSTextTwo = "invalid_sms_text_two"
	InvalidSMSTitle = "invalid_sms_title"
	InvalidMobileNumber = "invalid_mobile_number"
	InvalidTwoWaySmsFunction "invalid_two_way_sms"
	InvalidType ="invalid_type"
	InvalidWaitReturnSMS "invalid_wait_return_sms"
	InvalidSoftbankSMSText = "invalid_softbank_sms_text"
	IPAddressPriorBlock = "ip_address_prior_block"
	MethodNotAllowed = "method_not_allowed"
	SMSIDNotUnique = "sms_id_not_unique"
	SMSNotFound = "sms_not_found"
	SDPBasicSMSTextTooLong = "sdp_basic_sms_text_too_long"
	SDPReminderTextTooLong = "sdp_reminder_text_too_long"
	SoftbankSMSTextTooLong = "softbank_sms_text_too_long"
	SoftbankReminderTextTooLong = "softbank_reminder_text_too_long"
	RakutenMainTextTooLong = "rakuten_main_text_too_long"
	RakutenReminderTextTooLong = "rakuten_reminder_text_too_long"
	ReplyIDNotFound = "reply_id_not_found"
	ResendingParametersChangeFailure = "resending_parameters_change_failure"
	SendFailure = "send_failured"
	Success = "success"
	TemporaryUnavailable = "temporary_unavailable"
	URLTooLong = "url_too_long"
)

// APIResponse struct
type APIResponse struct {
	StatusCode  string
	Name        string
	Description string
}
